version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: homecooked-postgres
    environment:
      POSTGRES_DB: homecooked
      POSTGRES_USER: homecooked_user
      POSTGRES_PASSWORD: homecooked_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

volumes:
  postgres_data: